### ISSUE TITLE
Alt Attribute

### ISSUE THREAD

**Issue by jim-rosales** [narokoe/prj-rev-bwfs-tea-cozy#1]
Great job including the [alt attribute](https://en.wikipedia.org/wiki/Alt_attribute) on all your images!

https://github.com/narokoe/prj-rev-bwfs-tea-cozy/blob/02b8ae525eaefa029ce8611c3dca61d55b0b950b/Tea%20Cozy/index.html#L13

**Comment by narokoe** [comment]
Thanks. :)
