### ISSUE TITLE
HTML Comments

### ISSUE THREAD

**Issue by jim-rosales** [narokoe/prj-rev-bwfs-tea-cozy#2]
Fantastic job commenting your file!

https://github.com/narokoe/prj-rev-bwfs-tea-cozy/blob/02b8ae525eaefa029ce8611c3dca61d55b0b950b/Tea%20Cozy/index.html#L10

**Comment by narokoe** [comment]
It makes it so much easier to keep track of what is happening.  I really like utilizing comments.  Thank you!
