### ISSUE TITLE
Alternate Approach

### ISSUE THREAD

**Issue by jim-rosales** [narokoe/prj-rev-bwfs-tea-cozy#3]
It's not very good practice having multiple `<br />` following each other. The better approach would have been to have the subsequent text inside `<p>` tags.

For example:
```HTML
<div class="location">
  <h3>Downtown</h3>
  <p>384 West 4th St</p>
  <p>Suite 108</p>
  <p>Portland, Maine</p>
</div>
```

https://github.com/narokoe/prj-rev-bwfs-tea-cozy/blob/02b8ae525eaefa029ce8611c3dca61d55b0b950b/Tea%20Cozy/index.html#L74

**Comment by narokoe** [comment]
That makes more sense! 👍  I was at a loss, and did not think of that. Thank you
