### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [narokoe/prj-rev-bwfs-tea-cozy#5]
Grade: Meets Expectations

Summary:
Tyler, congrats on finishing the Tea Cozy project! Overall you did an excellent job making sure your HTML and CSS files were readable considering you commented both and made use of whitespace appropriately. You also did a great job making sure to include the alt attribute for all your images as it increases the [accessibility](https://www.codecademy.com/articles/accessibility) of your project.  

Although you did an excellent job in certain areas, visually your project did have some issues. For example, the navigation text wasn't right aligned, and a couple of other visual discrepancies were present. I suggest you take a look at this [HTML](https://gist.github.com/jim-rosales/46f2f87823e2546e3e1da4427e72bb48) and [CSS](https://gist.github.com/jim-rosales/f7e0153c0bb6a2c9563d415b9b4d44dc) solution and download them to see how this page differs from yours and see how you can modify your code to match regarding the visual aspect.

**Comment by narokoe** [comment]
I'm not going to lie, I struggled through this more than I had hoped I would.   Things I just couldn't figure out were, navbBar alignment, monthly image gap between 4 and 5 and the spacing on the locations on the bottom. I tried so many options and couldn't get it. 

In addition, I know my code got super messy toward the end of my 1800th try, so apologies for that! 

Thank you for the code, I will for sure be going through it and trying this project again in my free time.
